server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/springbootdubbo
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    mybatis:
      type-aliases-package:  domain

  redis:
    jedis:
      pool:
        max-active: 3000
        max-wait: 5000
        max-idle: 0
    host: 139.224.22.52
    port: 6379
    password: 19971001zx
    timeout: 7200