server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/springbootdubbo
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    mybatis:
      type-aliases-package:  domain